import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [entrada, setEntrada] = useState(0);
  const [saida, setSaida] = useState(0);
  const [total, setTotal] = useState(0);

  function calcularHoras(event) {
    event.preventDefault();
    const totalHoras = saida - entrada;
    setTotal(Number(totalHoras.toFixed(2)));
  }

  return (
    <>
      <Head>
        <title>Calculadora de Horas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="h-screen flex flex-col px-8 lg:px-72 justify-center">
          <h1 className="text-white items-center text-center font-extrabold text-3xl mb-12">Calculadora de Horas</h1>
          <form
            onSubmit={calcularHoras}
            className="flex flex-col"
          >
              <label htmlFor="entrada" className="text-white">
                Hora de Entrada:
              </label>
              <input
                type="text"
                inputMode="numeric"
                id="entrada"
                name="entrada"
                min="0"
                max="23"
                value={entrada}
                onChange={(event) => setEntrada(event.target.value)}
                required
                className="py-2 px-2 rounded-lg bg-transparent border border-neutral-900 text-neutral-500 focus:outline-none"
              />
            <br />
            <label htmlFor="saida" className="text-white">
              Hora de Saída:
            </label>
            <input
              type="text"
              inputMode="numeric"
              id="saida-minutos"
              name="saida-minutos"
              min="0"
              max="59"
              value={saida}
              onChange={(event) => setSaida(event.target.value)}
              required
              className="py-2 px-2 rounded-lg bg-transparent border border-neutral-900 text-neutral-500 focus:outline-none read-only:bg-stone-800"
            />
            <br />
            <label htmlFor="total" className="text-white">
              Total de Horas Trabalhadas:
            </label>
            <input
              type="text"
              id="total"
              name="total"
              value={total}
              readOnly
              className="py-2 px-2 rounded-lg bg-neutral-900 border font-extrabold border-neutral-900 text-neutral-500 focus:outline-none cursor-not-allowed"
            />
            <br />
            <input type="submit" value="Calcular" className="text-white bg-blue-700 rounded-lg py-3 font-bold cursor-pointer hover:bg-blue-600 duration-75"/>
          </form>
          <span className="text-stone-900 text-center mt-40">Criado por <a href="https://github.com/joseeugeniio" className="hover:underline">José Eugênio</a></span>
        </div>
      </main>
    </>
  );
}
